sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t quraian/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true quraian/docker-react npm run test -- --forceExit
